<?php

namespace HazAClass\System\Collection;

require_once dirname(__FILE__).'/../../../../HazAClass/System/Collection/ArrayList.php';

/**
 * Test class for ArrayList.
 * Generated by PHPUnit on 2011-03-09 at 11:26:27.
 */
class ArrayListTest extends AbstractListTest
{

	protected function setUp()
	{
		$this->list = new ArrayList();
	}

	protected function tearDown()
	{
		$this->list = null;
	}

	public function ElementDataProvider()
	{
		return array(
			array(0, 1, 'abc', 'dfg'),
			array(4, 7, 'fsddfadsf', 'sfadsgasgasd'),
		);
	}
}

?>
