<?php

namespace HazAClass\System\Xml;

require_once dirname(__FILE__).'/../../../../HazAClass/System/Xml/XmlAttribute.php';

/**
 * Test class for XmlAttribute.
 * Generated by PHPUnit on 2011-03-21 at 18:43:43.
 */
class XmlAttributeTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var XmlAttribute
	 */
	protected $xmlAttr;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->xmlAttr = new XmlAttribute("TestName", "TestValue");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->xmlAttr = null;
	}

	/**
	 * @todo Implement testAddNode().
	 */
	public function testAddNode()
	{
	
	}

	/**
	 * @todo Implement testRemoveNode().
	 */
	public function testRemoveNode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHasChildNodes().
	 */
	public function testHasChildNodes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetParentNode().
	 */
	public function testSetParentNode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRender().
	 */
	public function testRender()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
