<?php

namespace HazAClass\System\Xml;

require_once dirname(__FILE__).'/../../../../HazAClass/System/Xml/XmlAttribute.php';

/**
 * Test class for XmlAttribute.
 * Generated by PHPUnit on 2011-03-21 at 18:43:43.
 */
class XmlAttributeTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var XmlAttribute
	 */
	protected $xmlAttr;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->xmlAttr = new XmlAttribute("TestName", "TestValue");
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->xmlAttr = null;
	}

	/**
	 * @todo Implement testHasChildNodes().
	 */
	public function testHasChildNodes()
	{
		$this->assertFalse($this->xmlAttr->HasChildNodes());
	}

	/**
	 * @todo Implement testSetParentNode().
	 */
	public function testSetParentNode()
	{
		$this->assertNull($this->xmlAttr->GetParentNode());
		$element = new XmlElement('html');
		$this->xmlAttr->SetParentNode($element);
		$this->assertSame($element, $this->xmlAttr->GetParentNode());
	}

	/**
	 * @todo Implement testRender().
	 */
	public function testRender()
	{
		$this->assertEquals('TestName="TestValue"', $this->xmlAttr->Render());
	}

}

?>
