<?php

namespace HazAClass\System\Xml;

require_once dirname(__FILE__).'/../../../../HazAClass/System/Xml/XmlDocument.php';

/**
 * Test class for XmlDocument.
 * Generated by PHPUnit on 2011-03-21 at 18:43:43.
 */
class XmlDocumentTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var XmlDocument
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new XmlDocument();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		$this->object = null;
	}
	
	public function testGetRootNode()
	{
		$xml = new XmlElement('html');
		
		$this->object->SetRootNode($xml);
		$this->assertSame($xml, $this->object->GetRootNode());
	}

	/**
	 * @todo Implement testRender().
	 */
	public function testRender()
	{
		$xml = new XmlElement('html');
		
		$this->object->SetRootNode($xml);
		
	}

	/**
	 * @todo Implement testToString().
	 */
	public function testToString()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
