<?php

namespace HazAClass\System\Xml;

require_once dirname(__FILE__).'/../../../../HazAClass/System/Xml/XmlNode.php';

/**
 * Test class for XmlNode.
 * Generated by PHPUnit on 2011-03-21 at 18:43:42.
 */
abstract class XmlNodeTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var XmlNode
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
	
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	public function testAddNode()
	{
		$this->object->AddNode(new XmlAttribute('test', 'testvalue'));
		$this->object->AddNode(new XmlElement('body'));
		$this->assertEquals(2, $this->object->count());
	}

	public function testRemoveNode()
	{
		$attr = new XmlAttribute('test', 'testvalue');
		$node = new XmlElement('body');
		$this->object->AddNode($attr);
		$this->object->AddNode($node);
		$this->assertEquals(2, $this->object->count());
		$this->object->RemoveNode($node);
		$this->object->RemoveNode($attr);
		$this->assertEquals(0, $this->object->count());
	}

	/**
	 * @todo Implement testSetParentNode().
	 */
	public function testSetParentNode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetParentNode().
	 */
	public function testGetParentNode()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHasParentNode().
	 */
	public function testHasParentNode()
	{
		$this->assertFalse($this->object->HasParentNode());
	}

	/**
	 * @todo Implement testHasChildNodes().
	 */
	public function testHasChildNodes()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetName().
	 */
	public function testGetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetName().
	 */
	public function testSetName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRender().
	 */
	public function testRender()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
